spring:
  application:
    name: chatApp

  datasource:
    url: jdbc:postgresql://localhost:5432/chat_db
    username: postgres
    password: Saurabh*789


  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    .enabled: true

springdoc:
  swagger-ui:
    path: /api-docs
  api-docs:
    path: /openapi



